### PR TITLE
Modular gui menu

### LINKED ISSUE #79: GUI implementation
Use branch 'gui-integration' to make a gui using java swing/etc and PR for peer review.

### PR DESCRIPTION
**Pull request by JonathanGrant92**
Helps close #79 by making Kevin's gui more modular/ less hard-coded.

### CODE REVIEW

**Review by kevvo15 — CHANGES_REQUESTED** [review]
Overall, the new GUI implementation is great. It does have a better approach to the design patterns that we learned in class. My only comment is that the dialog text at the bottom of the GUI does not always fit all the information that is displayed on it, despite having a scroll bar (See attachment). Perhaps changing the size should address this? Another thing is that the feedback in the dialog box should change from "nothing to show" in some instances to actual feedback or something along those lines so the user knows what is going on. Notice if you create a product, the dialog box displays "nothing to show," when instead it would be better to display "product created successfully." Other than that, everything else seems to work perfectly fine! These changes are very minor, but would improve the user experience. 

Screen Shot 2020-11-12 at 1 37 18 PM

**Comment by JonathanGrant92** [comment]
> Overall, the new GUI implementation is great. It does have a better approach to the design patterns that we learned in class. My only comment is that the dialog text at the bottom of the GUI does not always fit all the information that is displayed on it, despite having a scroll bar (See attachment). Perhaps changing the size should address this? Another thing is that the feedback in the dialog box should change from "nothing to show" in some instances to actual feedback or something along those lines so the user knows what is going on. Notice if you create a product, the dialog box displays "nothing to show," when instead it would be better to display "product created successfully." Other than that, everything else seems to work perfectly fine! These changes are very minor, but would improve the user experience.
> 
> Screen Shot 2020-11-12 at 1 37 18 PM

Thank you for bringing these to my attention. I will address them tonight!

**Review by kevvo15 — APPROVED** [review]
The dialog box functions perfect now! As does the scroll bar, so these changes on the GUI are set to be merged in my opinion. Great job!

**Comment by JonathanGrant92** [comment]
> The dialog box functions perfect now! As does the scroll bar, so these changes on the GUI are set to be merged in my opinion. Great job!

Okay, thank you. I just did another commit, one thing led to another, and I debugged the OrderDatabase.processOrders of awkward IO output. There are still a few issues with it, but that method should be much more readable now. And yes, I probably should have pull another branch for that, sorry.

**Review by domschneider — APPROVED** [review]
I met with Jonathan today to discuss a few questions I had. So I just want to give my approval of this pull request after clarifying with him.

**Pull request merged**
