### PR TITLE
BuyerEvent updateQuantity() method

### PR DESCRIPTION
**Pull request by kevvo15**
- I initialized a database that holds the inventory
- updateQuantity() method now uses BuyerEvent object as a parameter.
- As of now, the updateQuantity() method DOES change the quantity of a product appropriately given its product_id
- However, it does NOT update the actual inventory file when completed
- I think I might be missing a few more things, but this is so you guys can see what direction I'm heading in

### CODE REVIEW

**Comment by kevvo15** [comment]
As of now, this program does the following:
- Initializes a database which reads from our inventory_team1.csv file
- Creates a BuyerEvent object using parameters from buyer_event.csv file
- Updates the quantity of a product given it's product_id
- Updates the database with the new quantity of the product

Note: If you run the program, I also printed out a single product BEFORE the simulation is run and again AFTER, so that you can visually see the changes to quantity. We may want to remove that before merging to the master branch.
Note: I made one small change to the search() method. I commented out a line of code that printed out where the product was found since it is not necessary for this method. I hope it does not affect the overall code too much; I wasn't sure how else to go about that.

**Comment by jfreda21** [comment]
Why is the new BuyerEvent Class file in the src/test directory? I believe IntelliJ has that directory marked as the Test module source? Should this be moved src/main?

**Comment by kevvo15** [comment]
> Why is the new BuyerEvent Class file in the src/test directory? I believe IntelliJ has that directory marked as the Test module source? Should this be moved src/main?

Yes, I believe so. Thanks for catching that! I'll move it to the correct location.

**Review by alexandersanford — APPROVED** [review]
Looks great! Excellent work. Glad we got the update method working smoothly.

**Pull request merged**
