### PR TITLE
Pr/48

### PR DESCRIPTION
**Pull request by Alejandro-Rojas**
@jfreda21 this will be use as our foundation. Added a OrderHistory class in the test files.

we need to append the data alex and kevin will be using for their event as we will be able to take that info and create an order history.
I have some data in the file already but it was for testing purposes only.
there is a csv file created called customerHistory.csv where it had customer order, date, and time. Will probably need to add more info depending what alex and kevin use.
please add to or make changes if needed.

### CODE REVIEW

**Comment by jfreda21** [comment]
Reviewed code written by Alejandro - waiting for @kevvo15 @alexandersanford

**Review by alexandersanford — APPROVED** [review]
All of this looks solid! Very cool to have the functionality to generate a CSV file built-in. Definitely a great step forward!

**Review by kevvo15 — APPROVED** [review]
Looks like a really good foundation for the order history. I will continue to work on gathering the data from the buyer event method in order to start testing it on "actual" customer orders.

**Comment by Alejandro-Rojas** [comment]
did some testing with orderhistory using junit, and also did more research on it. Waiting for an update from Alex and Kevins on their code.

**Comment by kevvo15** [comment]
I think the code is good to merge where it stands now. I'm also currently working on the jUnit testing for the buyer method. We can talk about how we'll link our programs during our huddle and issue pull requests from there.

**Comment by Alejandro-Rojas** [comment]
Merged to master

**Pull request merged**
